### ISSUE TITLE
GSC support for CentOS7.9

### ISSUE THREAD

**Issue by yzz127** [gramineproject/gsc#104]
CentOS8 supported by GSC has already reached its EOL that was planned at Dec. 31st 2021, and it is the only officially supported CentOS distro by GSC as of now.

CentOS7.9, on the other hand, is still widely used in production deployment. Its official EOL is June 30, 2024. As confidential computing gains industrial awareness, Gramine and GSC are their top choice to enter CC field and protect their business workload inside a TEE. 

We hope the GSC community consider supporting CentOS7.9 in GSC and Gramine, so as to enable the TEE protections for existing industrial partner to protect their workload. Thank you very much for your considerations!

**Comment by dimakuv** [comment]
@aneessahib @jinengandhi-intel @aniket-intelx Could you look into this support?

**Comment by aneessahib** [comment]
@yzz127 - can you list all the CentOS7.9 specific workarounds in place to get the PoC working?

**Comment by mkow** [comment]
I don't think we'll ever support CentOS 7, for multiple reasons:
- This distro was released in 2014. That was *8* years ago.
- The packages inside it are extremely old and are missing features, and had breaking API changes since then.
- The compiler shipped there is too old to be able to build Gramine.
- CentOS 7 support ends in just a year and a half.

So, summarizing, doing this would require us to undo the last few years of updates (i.e. downgrading all dependencies and their callsites), removing new C features we use, and many more. Basically, painfully moving our codebase back in time a few years, just to support an archaic distro which will be out of support in a year and a half.
