### ISSUE TITLE
Graminizing the Ubuntu 20.04 image fails with /bin/bash: Permission denied

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gsc#116]
## Description of the problem
Creating a graminized image of Ubuntu 20.04 with bash fails with /bin/bash: Permission denied. 

## Steps to reproduce

1. Create a test.sh with echo command
2. Create a Dockerfile with Entrypoint/CMD as /bin/bash test.sh and base os as 20.04
3. Build the docker base image
4. Graminize the application

**test.sh**
```
#!/bin/sh

echo "Hello Bash Shell Script"
/bin/bash sample.sh
```

**sample.sh**
```
#!/bin/sh

echo "Hello Sample Shell Script"
```

**Dockerfile:**
```
From ubuntu:20.04

RUN apt-get update

COPY test.sh .
COPY sample.sh .

CMD ["/bin/bash", "test.sh"]
```

## Expected results
When graminized application is running, it should return **"Hello Bash Shell Script"**

## Actual results
docker run  --device=/dev/sgx/enclave -it gsc-bash-test
```
Gramine is starting. Parsing TOML manifest file, this may take some time...
/usr/local/bin/entry_script_bash.sh: line 4: /bin/bash: Permission denied
```

## Additional information
In all ubuntu:20.04 based docker images, /bin is symlink to /usr/bin. Because of this GSC doesn't add any /bin file to trusted files.  Any bash script executed at run time having shebang #!/bin/bash is not able to access /bin/bash as it's not part of trusted files list. We get error:  /bin/bash: bad interpreter: Permission denied".

**Comment by dimakuv** [comment]
I think the root cause lies in GSC code. In particular, GSC has this limitation: https://github.com/gramineproject/gsc/blob/dbc17b6a118d0fb13411d3acd1f1dfc032b77b83/finalize_manifest.py#L58-L60

This means that GSC adds as trusted files only regular files and doesn't add symlinks.

I think we could relax this `if not os.path.isfile(filename)` check to also allow for symlinks, and then your problem with `ubuntu:20.04` will be solved. So I think this change in line 58 should be enough:
```
if not (os.path.isfile(filename) or os.path.islink(filename)):
```

(Well, probably more complicated than this one-liner... Needs some testing, but this is the general idea.)

**Comment by dimakuv** [comment]
Just to keep it for history, turned out not to be so easy. Because we have `followlinks=False` also: https://github.com/gramineproject/gsc/blob/dbc17b6a118d0fb13411d3acd1f1dfc032b77b83/finalize_manifest.py#L55

This precludes GSC to add e.g. `/bin/bash` because `/bin/` is a symlink directory (to `/usr/bin/`), so our GSC for loop doesn't enter the `/bin/` directory and thus doesn't find `/bin/bash`.

Simply changing to `followlinks=True` also doesn't work generally (and we hit this in real Docker images), because `os.walk(followlinks=True)` can lead to infinite recursion, see notes in https://docs.python.org/3/library/os.html#os.walk.

So the solution has to be more complicated, like this: https://stackoverflow.com/questions/36977259/avoiding-infinite-recursion-with-os-walk
