### ISSUE TITLE
graminize-sgx-sign fails with Permission Denied when using non-root image

### ISSUE THREAD

**Issue by creste** [gramineproject/gsc#142]
## Description of the problem

I created a non-root docker image, similar to #30.  When I try to sign the image using `gsc sign-image`, it throws this error:
>PermissionError: [Errno 13] Permission denied: '/etc/default/cacerts'

I verified `/etc/default/cacerts` is owned by root and _not_ readable by others:
```bash
$ ls -Fal /etc/default/cacerts 
-rw------- 1 root root 384 Jan  5 21:48 /etc/default/cacerts
```

I verified the `unsigned_image` stage of the [Dockerfile.common.sign.template](https://github.com/gramineproject/gsc/blob/master/templates/Dockerfile.common.sign.template#L2) file is running as my `nonroot` user, so that explains why there is a permissions error. If I change this:
```docker
FROM {{image}} as unsigned_image
COPY gsc-signer-key.pem /gramine/app_files/gsc-signer-key.pem
```
to this:
```
FROM {{image}} as unsigned_image
USER root
COPY gsc-signer-key.pem /gramine/app_files/gsc-signer-key.pem
```
Then that fixes the problem.

## Steps to reproduce
I'm using GSC at commit dbc17b6a118d0fb13411d3acd1f1dfc032b77b83.

1. Create a non-root docker image.  See #30 for an example.
2. Run `gsc build`
3. Run `gsc sign-image`

## Expected results
The image is succesfully signed.

## Actual results

This error is thrown:
```
 ---> Running in d6e27a33102b
spawn gramine-sgx-sign --key /gramine/app_files/gsc-signer-key.pem --manifest /gramine/app_files/entrypoint.manifest --output /gramine/app_files/entrypoint.manifest.sgx
Traceback (most recent call last):
  File "/gramine/meson_build_output/bin/gramine-sgx-sign", line 74, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/gramine/meson_build_output/bin/gramine-sgx-sign", line 34, in main
    expanded = manifest.expand_all_trusted_files()
  File "/gramine/meson_build_output/lib/python3.8/site-packages/graminelibos/manifest.py", line 180, in expand_all_trusted_files
    append_trusted_dir_or_file(trusted_files, tf, expanded)
  File "/gramine/meson_build_output/lib/python3.8/site-packages/graminelibos/manifest.py", line 72, in append_trusted_dir_or_file
    append_tf(trusted_files, path)
  File "/gramine/meson_build_output/lib/python3.8/site-packages/graminelibos/manifest.py", line 43, in append_tf
    trusted_files[path] = hash_ if hash_ is not None else hash_file_contents(path)
  File "/gramine/meson_build_output/lib/python3.8/site-packages/graminelibos/manifest.py", line 30, in hash_file_contents
    with open(path, 'rb') as f:
PermissionError: [Errno 13] Permission denied: '/etc/default/cacerts'
Removing intermediate container d6e27a33102b
```

**Comment by dimakuv** [comment]
@creste Yes, GSC will fail on such a scenario.

This is because GSC uses the root (`USER root`) only to install the packages/dependencies, and then switches back to normal non-root user: https://github.com/gramineproject/gsc/blob/f656037b664eb1ae55b2b8555755dbdcefefd067/templates/Dockerfile.common.build.template#L26-L27

This happens before the step of "signing the image"/"generating the final manifest", in particular this part: https://github.com/gramineproject/gsc/blob/f656037b664eb1ae55b2b8555755dbdcefefd067/templates/Dockerfile.common.build.template#L61

So your exerienced error is expected, actually...

I wonder if GSC should just skip such unreadable-by-current-user files, e.g. by adding `os.access(file, os.R_OK)` check somewhere in here: https://github.com/gramineproject/gsc/blob/f656037b664eb1ae55b2b8555755dbdcefefd067/finalize_manifest.py#L72-L78

@aneessahib @jkr0103 @mkow @woju What do you think about the proposal?

**Comment by dimakuv** [comment]
I was looking at this, and remembered that we had a similar problem in Gramine itself. However, there we fixed it only for **directory traversal**, not the explicit files, like in this GSC case: https://github.com/gramineproject/gramine/blob/cd6a9cca9585110a9bcd5c63dcc75b5c4d49466b/python/graminelibos/manifest.py#L68-L70

I will submit a quick PR that fixed this particular case now.

**Comment by dimakuv** [comment]
@creste Could you check https://github.com/gramineproject/gsc/pull/143?

**Comment by creste** [comment]
@dimakuv - #143 fixed it.  Thank you!

**Comment by dimakuv** [comment]
> I was looking at this, and remembered that we had a similar problem in Gramine itself. However, there we fixed it only for **directory traversal**, not the explicit files, like in this GSC case: https://github.com/gramineproject/gramine/blob/cd6a9cca9585110a9bcd5c63dcc75b5c4d49466b/python/graminelibos/manifest.py#L68-L70

Before I forget why I didn't want to modify the Gramine core (to add this check for the case for explicit files):
- In core Gramine, if a person writes a manifest with the file explicitly, then it makes sense to error out if this file is inaccessible. So we shouldn't add such a check and silently ignore the file.
- But in GSC, the manifest is generated automatically by the tool, so it makes sense to silently ignore such inaccessible files rather than erroring out.

**Comment by creste** [comment]
@dimakuv - Do you happen to know when #143 will be merged into `master`?

**Comment by dimakuv** [comment]
@creste Done, merged.
