### ISSUE TITLE
[Metaissue] Changing the license of GSC

### ISSUE THREAD

**Issue by dimakuv** [gramineproject/gsc#161]
## Description of the problem

GSC doesn't have a separate license from the core Gramine project. In fact, the license is missing from this repository. We must add the license.

Historically, GSC lived in the same repository as the core Gramine project (at that time called Graphene): https://github.com/gramineproject/graphene/tree/master/Tools/gsc. So GSC inherited the LGPL v3 license: https://github.com/gramineproject/graphene/blob/master/LICENSE.txt.

However, the question was raised whether the LGPL license is suitable for the GSC project. See e.g. #154. Indeed, the internal recommendation for us was to use the **BSD 3 license**.

I collected the list of contributors who contributed a significant number of (sufficiently big) PRs. This list was collected via:
-  `gramineproject/gsc$ git log | grep "Signed-off-by\|Co-authored-by" | sort`
- doing some manual review of commits of separate authors from the list above
- checking the commit message of the very first commit in this repo: https://github.com/gramineproject/gsc/commit/d79ea25af3fb3c908dc882a03bcdca8451ebe154

The resulting list looks like this (no particular order):
- [x] Li Lei, via his Intel manager Mona Vij, see https://github.com/gramineproject/gsc/issues/161#issuecomment-1691820125
- [x] Anjo Vahldiek-Oberwagner
- [x] Dmitrii Kuvaiskii
- [x] Michał Kowalczyk
- [x] Veena Saini
- [x] Wojtek Porczyk
- [x] Anees Sahib
- [x] Abin Mathew
- [x] Anjali Rai
- [x] Jitender Kumar
- [x] Kailun Qin
- [x] Vijay Dhanraj
- [x] Sonali Saha

## Actions required
1. Choose the new license for this repo (the suggestion is **BSD 3-clause**)
2. Obtain explicit consent from every of the aforementioned contributors that they are Ok to change the license from LGPL v3 to BSD 3-clause.

**Comment by veenasai2** [comment]
I agree to changing the license to BSD 3-clause.

**Comment by kailun-qin** [comment]
I agree to changing the license to BSD 3-clause. Thanks!

**Comment by mkow** [comment]
I agree to change the license to BSD 3-clause.

**Comment by anjalirai-intel** [comment]
I agree to change the license to BSD 3-clause.

**Comment by vahldiek** [comment]
I also agree to change the license to BSD 3-clause. Thanks!

**Comment by woju** [comment]
What is wrong with LGPL-3? IIUC it doesn't affect the application/container that is being packaged, but I don't think this project should be up for grabs for people who would like to just take it over and don't contribute back their templates or sth.

**Comment by amathew3** [comment]
I agree to change the license to BSD 3-clause.

**Comment by sahason** [comment]
I agree to changing the license to BSD 3-clause.

**Comment by vijaydhanraj** [comment]
I agree to change the license to BSD 3-clause.

**Comment by aneessahib** [comment]
> What is wrong with LGPL-3? IIUC it doesn't affect the application/container that is being packaged, but I don't think this project should be up for grabs for people who would like to just take it over and don't contribute back their templates or sth.

GSC is after-all a wrapper to help people use Gramine with docker. And we may not be able accommodate everyone's production needs here. For example the recent issue with new Meson version - there's an argument that we should pin the versions in GSC itself, but the flip side as we might call it is that we wont have the latest secure versions of packages by default. Changing the license to BSD 3-clause will help open up such options to users where they can pin to specific package versions and be compliant in their own production environments, while we continue to take the high ground of using only the latest most secure versions.

**Comment by dimakuv** [comment]
I agree with @aneessahib explanation. We had two customers already asking about the change of the license.

@woju WDYT?

> I don't think this project should be up for grabs for people who would like to just take it over and don't contribute back their templates or sth.

...Contribute back the templates that we'll never merge :) Many GSC tweaks are very customer-specific; GSC will not benefit from a bunch of super-corner-case templates.

**Comment by woju** [comment]
This explanation is incorrect. With LGPL-3+ there's also nothing that prevents people from privately forking GSC and pinning whatever dependencies. They just need to share the source (only with people who they distribute GSC to). It's not AGPL where they would have to share with whoever interacts with the code. Maybe they even don't need to share the templates at all: I'm not sure if the templates themselves, if they keep them separate from the main code, need to be licenced under LGPL — LGPL allows for linking with code licenced under different terms — but that would probably require legal interpretation.

> GSC will not benefit from a bunch of super-corner-case templates.

They won't need to share them with us in the first place, and I don't think there's any real difference between BSD and LGPL in this area, but that's not the point. What GSC would really not benefit from is turning it into closed source, proprietary, obfuscated thingy (yes, you can obfuscate both Python and Jinja), compatible only with `$CLOUD`, and this is what I'm afraid is being done here. Sorry, but I just don't think we're relicencing our code into permissive licence.

**Comment by woju** [comment]
"Asking them to publish" is oversimplification. Maybe there's a place in GSC or gramine which should be made adjustable, but currently isn't. One of them is already identified (signing), but there are possibly others, which might have not been identified. I understand people might not want to share all tweaks, but in such case they should approach us and ask for a knob (like a `{% block %}` in a template) to be adjusted. That way they won't have to publish their specific tweak, but the wider community will still benefit from this optional feature.

This model already works well in main Gramine repo: we have CPU-specific overrides, but there are only `x86_64` subdirectories, because PPC64 fork is AFAIK private and haven't seen the light of day (at least I haven't seen it). But the maintainer of this fork works with us on those adjustment points and when we miss something, then he comes with a bug and/or patch.

But what really concerns me is a scenario, where some CSP wanted to do some "Gramine Integration for $CLOUD" and allowed only their proprietary tool to be a wrapper around Gramine. So they would take GSC (and/or Gramine itself) and repurpose them under the pretense of some proprietary template or whatever. Then close it down, and at a right moment would make a slightly incompatible change in the direction of EEE (Embrace, Extend, Extinguish).

There were several projects (mostly databases or database-like software like MongoDB or ElasticSearch), which were originally licenced under permissive terms (usually one of BSD licence variants, sometimes MIT/X11/Expat). Then AWS came and deployed those projects as a "managed" solutions, adding some changes and not contributing anything (neither code nor money) to original projects. This took resources away from said projects (split/destroyed community and deprived the firms from revenue to pay to programmers). In response those projects took drastic measures like relicencing to non-free, source-available licences like SSPL to prevent AWS from taking over those projects. In response AWS forked some of those projects from last commit before licence change, and this cemented the split of the communities.

This is the scenario I want to avoid. We should keep LGPL licence to protect our project (Gramine proper and all related repos) from being taken over by a player with far more development resources and far greater customer base, which could be held hostage against us.

The difference between BSD and LGPL in this regard is that under BSD licence, CSPs can just get the repo, change it (the repo proper, not some addons like signing templates) and provide some compiled form to other people (their customers) while don't distributing the source. This is not a valid use of our project. Doing site-specific addons (which we won't merge, rightly so) is a valid use of GSC, but IIUC this is not prevented by LGPL. Doubly so, if they won't distribute changed gsc.

**Comment by dimakuv** [comment]
> I understand people might not want to share all tweaks, but in such case they should approach us and ask for a knob (like a `{% block %}` in a template) to be adjusted. That way they won't have to publish their specific tweak, but the wider community will still benefit from this optional feature.

How true is this statement "they won't have to publish their specific tweak"? Is LGPL preventing *only* re-distribution in this case?

E.g. looking at this: https://www.mend.io/blog/top-10-gpl-license-questions-answered/, I see the following statements:
> Modifications and derivative works. Users can modify the software and create derivative works based on it, but these modifications must also be distributed.
> If you modify an LGPL-licensed library, you must make the modified source code available but the application using the library can be distributed under different terms.

In other words, I don't see how your statement "they won't have to publish their specific tweak" corresponds to the LGPL interpretation.

Here's another top hit from a google search: https://opensource.stackexchange.com/questions/4804/modifying-an-lgpl-library-and-using-it-in-a-commercial-product. I can't parse the explanations other than:

> The net effect is that the copyleft of the LGPL 2.1 may be quite far reaching when the library is modified. Therefore, I would seek legal advice to confirm this.

Seriously, does *anyone* understand what LGPL actually means? Every time I try to google it in some other context other than "using an LGPL-licensed shared library", I bump into `who knows, seek legal advice`.

I believe this is the main problem for customers: there is no real guarantee that there won't be a lawsuit, since nobody seems to know exactly how LGPL applies to e.g. Python scripts. Any official links and references claiming otherwise (in the particular case of "LGPL on Python scripts and Jinja Dockerfile templates") would be helpful.

> This model already works well in main Gramine repo: we have CPU-specific overrides, but there are only x86_64 subdirectories, because PPC64 fork is AFAIK private and haven't seen the light of day (at least I haven't seen it). 

That's not true, and I think this case would definitely conflict with the LGPL license... https://github.com/stefanberger/gramine4ppc64

> But what really concerns me is a scenario, where some CSP wanted to do some "Gramine Integration for $CLOUD" and allowed only their proprietary tool to be a wrapper around Gramine. So they would take GSC (and/or Gramine itself) and repurpose them under the pretense of some proprietary template or whatever. Then close it down, and at a right moment would make a slightly incompatible change in the direction of EEE (Embrace, Extend, Extinguish).

Yes, I agree with this concern. Well, maybe the license should be not BSD, but also not LGPL? Are there licenses that are more appropriate to our GSC project, and **clearer in their statements**?

**Comment by donporter** [comment]
Is this something linux foundation could help with?  

I wonder if we could posit how we interpret "linking" in this context?  As in, we say this is LGPL, and what we mean by linking a python script - intuitively, that you can use this python script all you want as-is in a larger project with a different license, but you have to distribute any changes to the script itself.

It seems to me that the LGPL is what we want given Woju's goals, perhaps with some sort of meaningful clarification.

**Comment by dimakuv** [comment]
**NOTE**: When moving to a new license, we need to modify SPDX lines.

**Comment by woju** [comment]
After today's call, I agree to changing the licence to BSD 3-clause. Let's see what happens. If any CSP tries foul game against us, we can relicence it back from BSD 3-clause to LGPL-3 or another copyleft licence.

**Comment by dimakuv** [comment]
@rainfld Dear Li, could I kindly ask you to post your stance (as one of the early contributors to the GSC project) on this topic of changing the license of GSC from LGPL to BSD?

**Comment by nmwael** [comment]
Sorry to intrude, are there any timeline on end of the voting process and "implementation" of the new license if any?

**Comment by dimakuv** [comment]
Unfortunately @rainfld doesn't seem to be active, and I don't know other means to contact him.

On the other hand, I looked at the version of GSC that Li Lei worked on, here it is: https://github.com/gramineproject/graphene/tree/DEPRECATED/gsc/Tools

I verified that Li Lei didn't contribute any commits to our current GSC. You can double-check it by browsing the commit history of the GSC tool here: https://github.com/gramineproject/graphene/commits/master/Tools/gsc

I quickly looked at the original code of Li Lei:
- https://github.com/gramineproject/graphene/blob/DEPRECATED/gsc/Tools/gen_manifest
- https://github.com/gramineproject/graphene/blob/DEPRECATED/gsc/Tools/gsce

I would argue that there is **nothing** in the current GSC code that is left from the original version of Li Lei. Also, the very first commit of the "newly reborn" GSC tool was done by Anjo with only his copyright (no copyright from Li Lei): https://github.com/gramineproject/graphene/commit/f51aafddf3989db89fd4375c95430d9ab4d0fe29

**My summary**: I would argue that we **can drop** Li Lei from the list of developers whose approval we need to change the license. What do others think? @mkow @woju @aneessahib @kailun-qin @monavij @donporter ?

**Comment by monavij** [comment]
@rainfld Li Lei’s contributions were made under the scope of his employment with Intel Corporation. He is no longer an Intel employee and as copyright holder, Intel  approves the license change from LGPL-3 to BSD-3-Clause.
