### ISSUE TITLE
Why is the sgx token generated during runtime vs. during container build?

### ISSUE THREAD

**Issue by lead4good** [gramineproject/gsc#37]
Is it to support (insecure) arguments? 
https://github.com/gramineproject/gsc/blob/21b30f28e96d8ff83e1d7365ff84fea368d35bd3/templates/apploader.template#L14

**Comment by dimakuv** [comment]
No, that's how SGX tokens must be generated -- they **must** be generated on the same machine where the SGX enclave runs (so, during runtime and not during container build).

This is the SGX hardware requirement. It's not something that Gramine invented.

See also these explanations:
- https://github.com/gramineproject/graphene/issues/1050
- https://github.com/gramineproject/graphene/issues/1558

By the way, "SGX token" is actually EINITTOKEN (in SGX hardware terms). You can read about EINITTOKENs a bit here: https://gramine.readthedocs.io/en/latest/sgx-intro.html and for example here: https://community.intel.com/t5/Intel-Software-Guard-Extensions/Questions-about-launch-token-and-EINITTOKEN/td-p/1094870

The SGX token has nothing to do with insecure arguments.

**Comment by lead4good** [comment]
@dimakuv thanks for the clarification, all makes sense now.

Should I file an issue for gramine to remove the python dependency of `gramine-sgx-get-token`, to fullfill the goal in #13? _(Current implementation increases TCB (trusted files) by required software packages to generate manifest files or sgx-token (including Python), minimize these dependencies)_

**Comment by dimakuv** [comment]
> Should I file an issue for gramine to remove the python dependency of gramine-sgx-get-token, to fullfill the goal in #13? 

Sorry, I don't understand what you mean. Could you expand?

**Comment by lead4good** [comment]
Sure! As `gramine-sgx-get-token` needs to be run on the enclave executing machine it needs to be part of the container runtime. To reduce the python dependency of the container runtime, it would make sense to rewrite `gramine-sgx-get-token` in C.

**Comment by dimakuv** [comment]
Do you mean that you don't want to install/ship Python executables and libraries inside your slim container?

I see, this is reasonable. On the other hand, you still have the Intel SGX PSW/DCAP dependencies in the container, because you need them for Gramine to run properly (especially for SGX attestation). But I guess these dependencies do not require Python to be installed.

@woju @mkow Does this make sense for you?

**Comment by woju** [comment]
On Fri, Dec 03, 2021 at 02:10:19AM -0800, Dmitrii Kuvaiskii wrote:
> Do you mean that you don't want to install/ship Python executables and
> libraries inside your slim container?
> 
> I see, this is reasonable. On the other hand, you still have the Intel SGX
> PSW/DCAP dependencies in the container, because you need them for Gramine to
> run properly (especially for SGX attestation). But I guess these
> dependencies do not require Python to be installed.
> 
> @woju @mkow Does this make sense for you?

Yes, yeeting python from the container if it's just for gramine-sgx-get-token
is perfectly reasonable.

Also, because tokens aren't gramine-specific, in SGX SDK there should already
be something for this, so before writing anything I'd ask the reporter to
check SDK if there is anything to reuse.
