### ISSUE TITLE
Manifest and file creation during runtime

### ISSUE THREAD

**Issue by dzygann** [gramineproject/gsc#45]
Hi,

I'm run [Mosquitto](https://github.com/eclipse/mosquitto) in gsc. 
It creates the log file when the application is started and I get the following message after it is up and running

```
Error: Unable to open logfile /var/log/mosquitto/mosquitto.log for writing.
```

If I want to have a log file, I have to add the `/var/log/mosquitto/mosquitto.log` to the allowed files. 
But then I get the following message from Gramine: 
```
Gramine detected the following insecure configurations:

- loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
- sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)

Gramine will continue application execution, but this configuration must not be used in production!
```

If I add it to the `trusted_files` I get the following error message. 

```
Traceback (most recent call last):
  File "/gramine/meson_build_output/bin/gramine-sgx-sign", line 70, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/gramine/meson_build_output/bin/gramine-sgx-sign", line 30, in main
    expanded = manifest.expand_all_trusted_files()
  File "/gramine/meson_build_output/lib/python3.6/site-packages/graminelibos/manifest.py", line 193, in expand_all_trusted_files
    append_trusted_dir_or_file(trusted_files, tf, expanded)
  File "/gramine/meson_build_output/lib/python3.6/site-packages/graminelibos/manifest.py", line 57, in append_trusted_dir_or_file
    raise ManifestError(f'Cannot resolve {path}')
graminelibos.manifest.ManifestError: Cannot resolve /var/log/mosquitto/mosquitto.log
```
If I create the file in the dockerfile and add it to the `trusted_files` I get the messages:

```
Error: Unable to open logfile `/var/log/mosquitto/mosquitto.log` for writing.
error: Disallowing create/write/append to a trusted file '/var/log/mosquitto/mosquitto.log'
```

Is the `allowed_files` the only way to make this file available for the application?

**Comment by dimakuv** [comment]
There are several solutions, depending on your exact circumstances. I'm assuming that you want to have a properly-enabled production-ready high-security Mosquitto workload running inside the SGX enclave (in other words, not just for testing). I'm also assuming that Mosquitto uses this file only for writing (and never for reading, otherwise the attacker could put some malicious contents and break Mosquitto).

You should ask yourself a question: what is contained in this Mosquitto log file `/var/log/mosquitto/mosquitto.log`? Two possibilities:
1. Contents of this file contain security-critical messages, e.g., this file leaks confidential data, or leaks which connections from which clients occurred at which time (depends on your threat model, if this is a security risk for you or not), or exposes addresses of functions in enclave memory (this annuls Gramine's ASLR, again, you must decide if this is a significant security risk for you or not).
2. Contents of this file do *not* contain any security-critical messages. For example, the log file simply dumps some statistics periodically, and you don't care that this statistics can be analyzed by the attacker.

If you have option 2, then you don't care and just use `sgx.allowed_files = "/var/log/mosquitto/mosquitto.log"`. Gramine *will print* a warning about this, always. Is this something that you find annoying and misleading? You can always move this Gramine log to a separate file using `loader.log_file = "..."`.

If you have option 1, then you must not use `sgx.allowed_files`. You can not use `sgx.trusted_files` as well (they are only for read-only files). So you have several options:
- Configure Mosquitto in such a way so it *never* uses this log file.
- Configure Mosquitto in such a way so it dumps the log into your specified file. Then, you can specify a dummy `/dev/null` as a file (and then the log is written to nowhere) or a file on `tmpfs` Gramine FS mount point (and then the log becomes in-enclave-only and ephemeral).
- Use `sgx.protected_files`.

**Comment by dzygann** [comment]
Hi @dimakuv 
thanks for the detailed explanation!

I would like to create my setup as you describe here:

> Configure Mosquitto in such a way so it dumps the log into your specified file. ...  file on tmpfs Gramine FS mount point (and then the log becomes in-enclave-only and ephemeral).

Do you have documentation on how to achieve this?

**Comment by mkow** [comment]
https://gramine.readthedocs.io/en/latest/manifest-syntax.html#fs-mount-points ;)

**Comment by dzygann** [comment]
Hi,

this works for me :) Thank you very much!

One last question :) Can I also get rid of this message `loader.insecure__use_cmdline_argv = true`?  

If I set the property to `false` in my manifest, I get the error:

```
Exception: Duplicate key with different values found: `loader.insecure__use_cmdline_argv`
```

I'm also unsure what is the consequence of this. 
Would I be still able to set the CMD in the `dockerfile` and does it work?
Would I be still able to run the docker with overridden arguments?

**Comment by dimakuv** [comment]
You are not supposed to add `loader.insecure__use_cmdline_argv` in the manifest file used by GSC.

GSC already controls this manifest option, via the `--insecure-args` command-line option to `./gsc build`. See: https://gramine.readthedocs.io/projects/gsc/en/latest/#cmdoption-gsc-build-insecure-args

I bet you specify this command-line option when you perform `./gsc build`. Simply remove this option, and there will be no `loader.insecure__use_cmdline_argv = true` in the final manifest file, and you won't see the message from Gramine.

> Would I be still able to set the CMD in the dockerfile and does it work?

Yes, if the `--insecure-args` command-line option is omitted from `./gsc build` command, then GSC uses `ENTRYPOINT` + `CMD` values from the base Docker image. For some context, see https://stackoverflow.com/a/53544006/6325371. For GSC code, see https://github.com/gramineproject/gsc/blob/c4d5c2ddc7376645f396f069c06f6ba02aea2ee7/gsc.py#L52 and the usage of `binary_arguments`.

> Would I be still able to run the docker with overridden arguments?

No, you won't be able. Providing arbitrary arguments during Docker run is insecure.

**Comment by dzygann** [comment]
Hi @dimakuv 

> I bet you specify this command-line option when you perform ./gsc build.

Yes, you are right. I forget to remove the option 😄 

Thank you for clarifying! This helped me to understand the behaviour!

**Comment by dimakuv** [comment]
@dzygann Can we close this issue now?

**Comment by dzygann** [comment]
Yes, thanks again :)
